<?php

$doctors = [
    "Dr. Anita Dias",
    "Dr. Abhishek N.",
    "Dr. Prakash Babu M.N.",
    "Dr. Preetham Raj",
    "Dr. N. Praveenkumar",
    "Dr. Ambuja B.N.",
    "Dr. Sharmila.S",
    "Dr. Bhuvaneshwari",
    "Dr. Bhavya K.S",
    "Dr. Deepthi Laldayal",
    "Dr. Sheila Peter",
    "Dr. Annie Joji",
    "Dr. Uday Kumar",
    "Dr. Manohar C.V",
    "Dr. Vineetha J Malayil",
    "Dr. Conrad J Rasquinha",
    "Dr. Dhanpal",
    "Dr. Sharath",
    "Dr. Varun Manjunath",
    "Dr. Preethan K.N",
    "Dr. Ramesh Ranganathan",
    "Dr. Jeevak Shetty",
    "Dr. Keerthana Devasani",
    "Dr. Raghunandan",
    "Dr. Krishnaveni",
    "Dr. Nikhil Dhanpal",
    "Dr. V K Srinivas",
    "Dr. Ramakrishna Vignesh M",
    "Dr. Adrian Mario Dsouza",
    "Dr. Vishal Kulgod",
    "Dr. Umesh",
    "Dr. Avinash Sharma",
    "Mr. Mohammed Asfaque Patel",
    "Dr. Varun Kumar",
    "Ms. Arshiya B.E",
    "Dr. Sampath Kumar M.N.",
    "Dr. Anil Kumar N.",
    "Dr. Santhosh Saklecha"
];